# Generated by Django 3.0.4 on 2020-05-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='casePaper',
            field=models.CharField(default='something', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(default='1234567890', max_length=10),
        ),
    ]
