# Generated by Django 3.0.5 on 2020-05-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200523_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(default='Null', max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bloodGroup',
            field=models.CharField(default='Null', max_length=4),
        ),
    ]
