# Generated by Django 3.0.5 on 2020-05-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200524_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='casePaper',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(default='Null', max_length=10),
        ),
    ]
