# Generated by Django 3.0.5 on 2020-05-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200524_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='patient_name',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_fullname',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
