# Generated by Django 3.0.5 on 2020-05-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200524_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='patient_name',
        ),
    ]
